Dockerize for GitHub execution
Emm/shortcut_release_helper pull request #4
Opened 2023-07-07 16:51 UTC by jprosenbaum

2023-09-15 03:45 UTC, Emm commented
Hi! Sorry about being a bad maintainer and not being responsive, I never saw that PR. I think dockerizing the tool is a good idea, so I'll be happy to work with you on getting this merged.

You may want to start with rebasing your PR, I have just updated the dependencies.

2023-09-15 04:15 UTC, Emm requested changes

2023-09-15 04:15 UTC, Emm commented on shortcut_release_helper/src/shortcut.rs
> +            Regex::new(r"(?:\[sc-|\[ch|story/)(\d+)").expect("Could not compile SHORTCUT_RE");
Is `story` a prefix supported by Shortcut for linking commits to issues automatically? The [documentation](https://help.shortcut.com/hc/en-us/articles/360023113972-Associate-a-Git-branch-to-a-Story#git-custom) does not suggest it...

If it's not the case, this would be better as a separate PR.

If the idea is to support user-defined prefixes, why not. But this means making it configurable in `config.toml` (an optional array would be ideal). We would also need either to restrict the prefixes to something like `[a-zA-Z]+` (or be ready to escape characters.

One last point, your commit would also find a comment like `Unlike what we did for [sc-XXX], this is actually a good idea`. If the purpose is to find badly formatted commits like `   [sc-XXX]` I suggest to simply trim the string/allow `^\s*` at the start.

2023-09-15 04:15 UTC, Emm commented on shortcut_release_helper/Cargo.toml
You can remove this commit and rebase, I have updated `minijnja` to the latest version.

2023-09-15 04:15 UTC, Emm commented on shortcut_release_helper/src/main.rs
> +#[clap(author, about, long_about = None, disable_version_flag = true)]
Good catch.

2023-09-18 20:34 UTC, jprosenbaum commented on shortcut_release_helper/src/shortcut.rs
> +            Regex::new(r"(?:\[sc-|\[ch|story/)(\d+)").expect("Could not compile SHORTCUT_RE");
I added story to the regex to cover missed associations but a story URL was in the PR history
`Story details: https://app.shortcut.com/xyz/story/####`

This was happening when a PR title did not reference the story ID, but a commit or the branch name linked to the story.   Shortcut was pushing story link annotation onto the PR.

This change would detect those instances and make sure they were associated correctly

2023-09-18 20:49 UTC, jprosenbaum commented
@Emm I have rebased the branch.

2023-09-19 06:35 UTC, Emm commented on shortcut_release_helper/src/shortcut.rs
> +            Regex::new(r"(?:\[sc-|\[ch|story/)(\d+)").expect("Could not compile SHORTCUT_RE");
All right, thanks. I'll have a look this week.

2023-09-24 05:57 UTC, Emm commented on shortcut_release_helper/src/shortcut.rs
> +            Regex::new(r"(?:\[sc-|\[ch|story/)(\d+)").expect("Could not compile SHORTCUT_RE");
> All right, thanks. I'll have a look this week.

More like next week I'm afraid :(

2023-10-04 07:07 UTC, Emm commented on Dockerfile
I have started testing it, unfortunately the OpenAPI generator blows up with a stack overflow error. We may need to pin that to a specific version if possible.

2023-10-05 20:01 UTC, jprosenbaum commented on Dockerfile
Can you post the error. I can look at it in a few days

2023-10-20 22:00 UTC, Emm commented
@jprosenbaum , I finally got around to working on this. Can you check out the `dockerize-for-github-execution` branch when you get the opportunity? The Dockerfile is based on your version, but somewhat shorter. The commits on the branch should make reasonably easy to follow what changed, but basically:
- no more `dos2unix`, we now use `.gitattributes` (which is also in `master`) to preserve Unix line endings for bash scripts
- no more `RUN chmod`, it is done by passing an option to `COPY`
- we download a specific release of the OpenAPI generator from Github
- we copy the lock file (we also the cached layer, but I think it's a good tradeoff)

2023-10-29 16:57 UTC, merged